FROM ubuntu:18.04
ENV DEBIAN_FRONTEND=noninteractive

#Install various Debian packages
RUN apt-get update
RUN apt-get install -y wget curl gcc g++ build-essential checkinstall libreadline-gplv2-dev libncursesw5-dev libsqlite3-dev tk-dev libgdbm-dev libc6-dev
RUN apt-get install -y libbz2-dev libffi-dev libssl-dev libncurses5-dev libtk8.6 libgdm-dev libdb4o-cil-dev libpcap-dev libcurl4-gnutls-dev libxml2-dev
RUN apt-get install -y libgit2-dev libzmq3-dev libharfbuzz-dev libfribidi-dev libfreetype6-dev libpng-dev libtiff5-dev libjpeg-dev libfontconfig1-dev graphviz

#Install R 4.1.0
RUN apt-get install -y --no-install-recommends software-properties-common dirmngr
RUN wget -qO- https://cloud.r-project.org/bin/linux/ubuntu/marutter_pubkey.asc | tee -a /etc/apt/trusted.gpg.d/cran_ubuntu_key.asc
RUN add-apt-repository "deb https://cloud.r-project.org/bin/linux/ubuntu $(lsb_release -cs)-cran40/"
RUN apt install -y --no-install-recommends r-base-core=4.1.0-1.1804.0 r-base-html=4.1.0-1.1804.0 r-doc-html=4.1.0-1.1804.0 r-base-dev=4.1.0-1.1804.0

#Install ViennaRNA
WORKDIR /bin
ADD https://www.tbi.univie.ac.at/RNA/download/sourcecode/2_4_x/ViennaRNA-2.4.14.tar.gz .
RUN tar -zxvf ViennaRNA-2.4.14.tar.gz
RUN ViennaRNA-2.4.14/configure --without-swig --without-forester --without-kinfold --without-rnalocmin && make && make install
WORKDIR /

#Install Python 3.7.1
RUN  cd /usr/src && \
     wget https://www.python.org/ftp/python/3.7.1/Python-3.7.1.tgz && \
     tar xzf Python-3.7.1.tgz && \
     cd Python-3.7.1 && \
     ./configure --enable-optimizations && \
     make altinstall
RUN pip3.7 install --upgrade pip
RUN  update-alternatives --install /usr/bin/python python /usr/bin/python3.6 1 &&\
     update-alternatives --install /usr/bin/python python /usr/local/bin/python3.7 2 &&\
     update-alternatives --set python /usr/local/bin/python3.7
RUN  update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.6 1 &&\
     update-alternatives --install /usr/bin/python3 python3 /usr/local/bin/python3.7 2 &&\
     update-alternatives --set python3 /usr/local/bin/python3.7

#Install R and Python packages
ADD requirements.txt .
ADD requirements.r .
RUN pip3.7 install -r requirements.txt >/dev/null 2>&1
RUN Rscript requirements.r

#Add BoostMEC scripts and example data (does not contain full repo)
ADD BoostMEC /BoostMEC

CMD ["bash"]
