install.packages("cli", repos='http://cran.rstudio.com/')
install.packages("rlang", repos='http://cran.rstudio.com/')
install.packages("devtools", repos='http://cran.rstudio.com/')
library(devtools)
install_version("gtools", version = "3.9.2")
install_version("janitor", version = "2.1.0")
install_version("tidyverse", version = "1.3.1")
install_version("TmCalculator", version = "1.0.1")
install_version("lightgbm", version = "3.3.2")
install_version("optparse", version = "1.7.3")
install_version("fs", version = "1.5.2")
